// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CompleteRequestStatus.
const (
	CompleteRequestStatusDone   CompleteRequestStatus = "done"
	CompleteRequestStatusFailed CompleteRequestStatus = "failed"
)

// Valid indicates whether the value is a known member of the CompleteRequestStatus enum.
func (e CompleteRequestStatus) Valid() bool {
	switch e {
	case CompleteRequestStatusDone:
		return true
	case CompleteRequestStatusFailed:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseService.
const (
	CrowdmonApi HealthResponseService = "crowdmon-api"
)

// Valid indicates whether the value is a known member of the HealthResponseService enum.
func (e HealthResponseService) Valid() bool {
	switch e {
	case CrowdmonApi:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for JobKind.
const (
	Chunk    JobKind = "chunk"
	Download JobKind = "download"
)

// Valid indicates whether the value is a known member of the JobKind enum.
func (e JobKind) Valid() bool {
	switch e {
	case Chunk:
		return true
	case Download:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	JobStatusClaimed JobStatus = "claimed"
	JobStatusDone    JobStatus = "done"
	JobStatusFailed  JobStatus = "failed"
	JobStatusPending JobStatus = "pending"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusClaimed:
		return true
	case JobStatusDone:
		return true
	case JobStatusFailed:
		return true
	case JobStatusPending:
		return true
	default:
		return false
	}
}

// AdminChunkWork defines model for AdminChunkWork.
type AdminChunkWork struct {
	// EndSeconds Example: 60
	EndSeconds int `json:"end_seconds"`

	// SegmentIndex Example: 0
	SegmentIndex int `json:"segment_index"`

	// StartSeconds Example: 0
	StartSeconds int `json:"start_seconds"`
}

// AdminJob defines model for AdminJob.
type AdminJob struct {
	// Attempts Example: 1
	Attempts int             `json:"attempts"`
	Chunk    *AdminChunkWork `json:"chunk,omitempty"`

	// ClaimedAt Example: 1754100000
	ClaimedAt *int `json:"claimed_at"`

	// ClaimedBy Example: carls-ubuntu-1
	ClaimedBy *string `json:"claimed_by"`

	// CreatedAt Example: 1754099000
	CreatedAt int `json:"created_at"`

	// FailureReason Example: video unavailable
	FailureReason *string `json:"failure_reason"`

	// HeartbeatAt Example: 1754100030
	HeartbeatAt *int `json:"heartbeat_at"`

	// Id Example: 1
	Id     int       `json:"id"`
	Kind   JobKind   `json:"kind"`
	Status JobStatus `json:"status"`

	// UpdatedAt Example: 1754100030
	UpdatedAt int `json:"updated_at"`

	// VideoId Example: dQw4w9WgXcQ
	VideoId string `json:"video_id"`

	// VideoUrl Example: https://www.youtube.com/watch?v=dQw4w9WgXcQ
	VideoUrl string `json:"video_url"`
}

// ChunkFanOut defines model for ChunkFanOut.
type ChunkFanOut struct {
	// Created Example: 20
	Created int `json:"created"`

	// Segments Example: 20
	Segments int `json:"segments"`

	// VideoId Example: dQw4w9WgXcQ
	VideoId string `json:"video_id"`
}

// ChunkWork defines model for ChunkWork.
type ChunkWork struct {
	// EndSeconds Example: 60
	EndSeconds int `json:"end_seconds"`

	// SegmentIndex Example: 0
	SegmentIndex int `json:"segment_index"`

	// StartSeconds Example: 0
	StartSeconds int `json:"start_seconds"`
}

// ClaimRequest defines model for ClaimRequest.
type ClaimRequest struct {
	// WorkerId Example: carls-ubuntu-1
	WorkerId string `json:"worker_id"`
}

// CompleteRequest defines model for CompleteRequest.
type CompleteRequest struct {
	// FailureReason Example: video unavailable
	FailureReason *string               `json:"failure_reason,omitempty"`
	Status        CompleteRequestStatus `json:"status"`

	// WorkerId Example: carls-ubuntu-1
	WorkerId string `json:"worker_id"`
}

// CompleteRequestStatus defines model for CompleteRequest.Status.
type CompleteRequestStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Example: invalid request
	Error  string             `json:"error"`
	Issues *[]ValidationIssue `json:"issues,omitempty"`
}

// FanOutRequest defines model for FanOutRequest.
type FanOutRequest struct {
	// DurationSeconds Example: 1200
	DurationSeconds int `json:"duration_seconds"`

	// Height Example: 1080
	Height int `json:"height"`

	// Title Example: Genshin Impact — Paimon
	Title *string `json:"title,omitempty"`

	// Width Example: 1920
	Width int `json:"width"`

	// WorkerId Example: carls-ubuntu-1
	WorkerId string `json:"worker_id"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Environment Example: production
	Environment string                `json:"environment"`
	Service     HealthResponseService `json:"service"`
	Status      HealthResponseStatus  `json:"status"`
}

// HealthResponseService defines model for HealthResponse.Service.
type HealthResponseService string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HeartbeatRequest defines model for HeartbeatRequest.
type HeartbeatRequest struct {
	// WorkerId Example: carls-ubuntu-1
	WorkerId string `json:"worker_id"`
}

// ImageFrame defines model for ImageFrame.
type ImageFrame struct {
	// Phash Example: af3c9e1b2d4f7a80
	Phash string `json:"phash"`

	// R2Key Example: dQw4w9WgXcQ/0042.500.jpg
	R2Key string `json:"r2_key"`

	// TimestampSeconds Example: 42.5
	TimestampSeconds float32 `json:"timestamp_seconds"`
}

// ImageReport defines model for ImageReport.
type ImageReport struct {
	// Images Example: 12
	Images int `json:"images"`

	// VideoId Example: dQw4w9WgXcQ
	VideoId string `json:"video_id"`
}

// Job defines model for Job.
type Job struct {
	// Attempts Example: 1
	Attempts int        `json:"attempts"`
	Chunk    *ChunkWork `json:"chunk,omitempty"`

	// Id Example: 1
	Id   int     `json:"id"`
	Kind JobKind `json:"kind"`

	// VideoId Example: dQw4w9WgXcQ
	VideoId string `json:"video_id"`

	// VideoUrl Example: https://www.youtube.com/watch?v=dQw4w9WgXcQ
	VideoUrl string `json:"video_url"`
}

// JobKind defines model for JobKind.
type JobKind string

// JobList defines model for JobList.
type JobList struct {
	Jobs []AdminJob `json:"jobs"`

	// Now Example: 1754100030
	Now int `json:"now"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// ReportImagesRequest defines model for ReportImagesRequest.
type ReportImagesRequest struct {
	// ConfigVersion Example: 2026-08-01-a
	ConfigVersion string `json:"config_version"`

	// DedupThreshold Example: 8
	DedupThreshold int `json:"dedup_threshold"`

	// FramesExtracted Example: 60
	FramesExtracted int `json:"frames_extracted"`

	// FramesKept Example: 12
	FramesKept int          `json:"frames_kept"`
	Images     []ImageFrame `json:"images"`

	// WorkerId Example: carls-ubuntu-1
	WorkerId string `json:"worker_id"`
}

// SubmitVideoRequest defines model for SubmitVideoRequest.
type SubmitVideoRequest struct {
	// Url Example: https://www.youtube.com/watch?v=dQw4w9WgXcQ
	Url string `json:"url"`
}

// ValidationIssue defines model for ValidationIssue.
type ValidationIssue struct {
	// Message Example: Invalid URL
	Message string `json:"message"`

	// Path Example: url
	Path string `json:"path"`
}

// VideoSubmission defines model for VideoSubmission.
type VideoSubmission struct {
	// JobId Example: 1
	JobId int `json:"job_id"`

	// VideoId Example: dQw4w9WgXcQ
	VideoId string `json:"video_id"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Status *JobStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// SubmitVideoJSONRequestBody defines body for SubmitVideo for application/json ContentType.
type SubmitVideoJSONRequestBody = SubmitVideoRequest

// ClaimJobJSONRequestBody defines body for ClaimJob for application/json ContentType.
type ClaimJobJSONRequestBody = ClaimRequest

// CompleteJobJSONRequestBody defines body for CompleteJob for application/json ContentType.
type CompleteJobJSONRequestBody = CompleteRequest

// FanOutJobJSONRequestBody defines body for FanOutJob for application/json ContentType.
type FanOutJobJSONRequestBody = FanOutRequest

// HeartbeatJobJSONRequestBody defines body for HeartbeatJob for application/json ContentType.
type HeartbeatJobJSONRequestBody = HeartbeatRequest

// ReportImagesJSONRequestBody defines body for ReportImages for application/json ContentType.
type ReportImagesJSONRequestBody = ReportImagesRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListJobs List jobs with their lease and failure state
	//
	// The operator's view of the queue. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
	//
	// Corresponds with GET /api/admin/jobs (the `ListJobs` operationId).
	ListJobs(ctx context.Context, params *ListJobsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AdminLogin Complete an Access login and return to the dashboard
	//
	// Exists to be navigated to, not fetched. Access gates the path, so an unauthenticated browser is sent through the login flow and only then redirected on to `/admin`.
	//
	// Corresponds with GET /api/admin/login (the `AdminLogin` operationId).
	AdminLogin(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitVideoWithBody Submit a YouTube URL for processing
	//
	// Creates the video row and enqueues its download job. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/admin/videos (the `SubmitVideo` operationId).
	SubmitVideoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubmitVideo Submit a YouTube URL for processing
	//
	// Creates the video row and enqueues its download job. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/admin/videos (the `SubmitVideo` operationId).
	SubmitVideo(ctx context.Context, body SubmitVideoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClaimJobWithBody Claim the next pending job
	//
	// Atomic: the claim is a single `UPDATE ... WHERE status='pending' ... RETURNING`, so two workers polling at once cannot take the same row.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/jobs/claim (the `ClaimJob` operationId).
	ClaimJobWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ClaimJob Claim the next pending job
	//
	// Atomic: the claim is a single `UPDATE ... WHERE status='pending' ... RETURNING`, so two workers polling at once cannot take the same row.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/jobs/claim (the `ClaimJob` operationId).
	ClaimJob(ctx context.Context, body ClaimJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteJobWithBody Report a held job as done or failed
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/jobs/{id}/complete (the `CompleteJob` operationId).
	CompleteJobWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteJob Report a held job as done or failed
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/jobs/{id}/complete (the `CompleteJob` operationId).
	CompleteJob(ctx context.Context, id int, body CompleteJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FanOutJobWithBody Record what a download probed, and enqueue its chunk jobs
	//
	// Phase two of CONTEXT.md §Q13's two-phase fan-out. Idempotent on `(video_id, segment_index)`, so a download reaped mid-fan-out re-runs without duplicating the segments that already exist.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/jobs/{id}/fanout (the `FanOutJob` operationId).
	FanOutJobWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FanOutJob Record what a download probed, and enqueue its chunk jobs
	//
	// Phase two of CONTEXT.md §Q13's two-phase fan-out. Idempotent on `(video_id, segment_index)`, so a download reaped mid-fan-out re-runs without duplicating the segments that already exist.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/jobs/{id}/fanout (the `FanOutJob` operationId).
	FanOutJob(ctx context.Context, id int, body FanOutJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeartbeatJobWithBody Renew the lease on a held job
	//
	// Called every 30s while a job is held. Missing heartbeats are what the reaper watches for; a job whose `heartbeat_at` goes stale returns to `pending`.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/jobs/{id}/heartbeat (the `HeartbeatJob` operationId).
	HeartbeatJobWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeartbeatJob Renew the lease on a held job
	//
	// Called every 30s while a job is held. Missing heartbeats are what the reaper watches for; a job whose `heartbeat_at` goes stale returns to `pending`.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/jobs/{id}/heartbeat (the `HeartbeatJob` operationId).
	HeartbeatJob(ctx context.Context, id int, body HeartbeatJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReportImagesWithBody Report the frames a chunk worker extracted, deduplicated and uploaded
	//
	// M8.4: writes the image rows and stamps the threshold and config version that produced them in the same batch, so a report can never leave the dataset with rows nobody's provenance covers. Idempotent on (video_id, timestamp_seconds), so a chunk reaped mid-report re-runs without duplicating rows (CONTEXT.md §Q14).
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /api/jobs/{id}/images (the `ReportImages` operationId).
	ReportImagesWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReportImages Report the frames a chunk worker extracted, deduplicated and uploaded
	//
	// M8.4: writes the image rows and stamps the threshold and config version that produced them in the same batch, so a report can never leave the dataset with rows nobody's provenance covers. Idempotent on (video_id, timestamp_seconds), so a chunk reaped mid-report re-runs without duplicating rows (CONTEXT.md §Q14).
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /api/jobs/{id}/images (the `ReportImages` operationId).
	ReportImages(ctx context.Context, id int, body ReportImagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth Liveness and deployment identity
	//
	// Corresponds with GET /health (the `GetHealth` operationId).
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListJobs List jobs with their lease and failure state
//
// The operator's view of the queue. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
//
// Corresponds with GET /api/admin/jobs (the `ListJobs` operationId).
func (c *Client) ListJobs(ctx context.Context, params *ListJobsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListJobsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AdminLogin Complete an Access login and return to the dashboard
//
// Exists to be navigated to, not fetched. Access gates the path, so an unauthenticated browser is sent through the login flow and only then redirected on to `/admin`.
//
// Corresponds with GET /api/admin/login (the `AdminLogin` operationId).
func (c *Client) AdminLogin(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAdminLoginRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SubmitVideoWithBody Submit a YouTube URL for processing
//
// Creates the video row and enqueues its download job. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/admin/videos (the `SubmitVideo` operationId).
func (c *Client) SubmitVideoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitVideoRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SubmitVideo Submit a YouTube URL for processing
//
// Creates the video row and enqueues its download job. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/admin/videos (the `SubmitVideo` operationId).
func (c *Client) SubmitVideo(ctx context.Context, body SubmitVideoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitVideoRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ClaimJobWithBody Claim the next pending job
//
// Atomic: the claim is a single `UPDATE ... WHERE status='pending' ... RETURNING`, so two workers polling at once cannot take the same row.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/jobs/claim (the `ClaimJob` operationId).
func (c *Client) ClaimJobWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClaimJobRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ClaimJob Claim the next pending job
//
// Atomic: the claim is a single `UPDATE ... WHERE status='pending' ... RETURNING`, so two workers polling at once cannot take the same row.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/jobs/claim (the `ClaimJob` operationId).
func (c *Client) ClaimJob(ctx context.Context, body ClaimJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewClaimJobRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CompleteJobWithBody Report a held job as done or failed
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/jobs/{id}/complete (the `CompleteJob` operationId).
func (c *Client) CompleteJobWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteJobRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CompleteJob Report a held job as done or failed
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/jobs/{id}/complete (the `CompleteJob` operationId).
func (c *Client) CompleteJob(ctx context.Context, id int, body CompleteJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteJobRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// FanOutJobWithBody Record what a download probed, and enqueue its chunk jobs
//
// Phase two of CONTEXT.md §Q13's two-phase fan-out. Idempotent on `(video_id, segment_index)`, so a download reaped mid-fan-out re-runs without duplicating the segments that already exist.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/jobs/{id}/fanout (the `FanOutJob` operationId).
func (c *Client) FanOutJobWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFanOutJobRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// FanOutJob Record what a download probed, and enqueue its chunk jobs
//
// Phase two of CONTEXT.md §Q13's two-phase fan-out. Idempotent on `(video_id, segment_index)`, so a download reaped mid-fan-out re-runs without duplicating the segments that already exist.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/jobs/{id}/fanout (the `FanOutJob` operationId).
func (c *Client) FanOutJob(ctx context.Context, id int, body FanOutJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFanOutJobRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// HeartbeatJobWithBody Renew the lease on a held job
//
// Called every 30s while a job is held. Missing heartbeats are what the reaper watches for; a job whose `heartbeat_at` goes stale returns to `pending`.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/jobs/{id}/heartbeat (the `HeartbeatJob` operationId).
func (c *Client) HeartbeatJobWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeartbeatJobRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// HeartbeatJob Renew the lease on a held job
//
// Called every 30s while a job is held. Missing heartbeats are what the reaper watches for; a job whose `heartbeat_at` goes stale returns to `pending`.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/jobs/{id}/heartbeat (the `HeartbeatJob` operationId).
func (c *Client) HeartbeatJob(ctx context.Context, id int, body HeartbeatJobJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeartbeatJobRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReportImagesWithBody Report the frames a chunk worker extracted, deduplicated and uploaded
//
// M8.4: writes the image rows and stamps the threshold and config version that produced them in the same batch, so a report can never leave the dataset with rows nobody's provenance covers. Idempotent on (video_id, timestamp_seconds), so a chunk reaped mid-report re-runs without duplicating rows (CONTEXT.md §Q14).
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /api/jobs/{id}/images (the `ReportImages` operationId).
func (c *Client) ReportImagesWithBody(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReportImagesRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReportImages Report the frames a chunk worker extracted, deduplicated and uploaded
//
// M8.4: writes the image rows and stamps the threshold and config version that produced them in the same batch, so a report can never leave the dataset with rows nobody's provenance covers. Idempotent on (video_id, timestamp_seconds), so a chunk reaped mid-report re-runs without duplicating rows (CONTEXT.md §Q14).
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /api/jobs/{id}/images (the `ReportImages` operationId).
func (c *Client) ReportImages(ctx context.Context, id int, body ReportImagesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReportImagesRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHealth Liveness and deployment identity
//
// Corresponds with GET /health (the `GetHealth` operationId).
func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListJobsRequest constructs an http.Request for the ListJobs method
func NewListJobsRequest(server string, params *ListJobsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/jobs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAdminLoginRequest constructs an http.Request for the AdminLogin method
func NewAdminLoginRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSubmitVideoRequest calls the generic SubmitVideo builder with application/json body
func NewSubmitVideoRequest(server string, body SubmitVideoJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubmitVideoRequestWithBody(server, "application/json", bodyReader)
}

// NewSubmitVideoRequestWithBody constructs an http.Request for the SubmitVideo method, with any body, and a specified content type
func NewSubmitVideoRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/videos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewClaimJobRequest calls the generic ClaimJob builder with application/json body
func NewClaimJobRequest(server string, body ClaimJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewClaimJobRequestWithBody(server, "application/json", bodyReader)
}

// NewClaimJobRequestWithBody constructs an http.Request for the ClaimJob method, with any body, and a specified content type
func NewClaimJobRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/claim")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCompleteJobRequest calls the generic CompleteJob builder with application/json body
func NewCompleteJobRequest(server string, id int, body CompleteJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCompleteJobRequestWithBody(server, id, "application/json", bodyReader)
}

// NewCompleteJobRequestWithBody constructs an http.Request for the CompleteJob method, with any body, and a specified content type
func NewCompleteJobRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s/complete", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewFanOutJobRequest calls the generic FanOutJob builder with application/json body
func NewFanOutJobRequest(server string, id int, body FanOutJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFanOutJobRequestWithBody(server, id, "application/json", bodyReader)
}

// NewFanOutJobRequestWithBody constructs an http.Request for the FanOutJob method, with any body, and a specified content type
func NewFanOutJobRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s/fanout", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHeartbeatJobRequest calls the generic HeartbeatJob builder with application/json body
func NewHeartbeatJobRequest(server string, id int, body HeartbeatJobJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHeartbeatJobRequestWithBody(server, id, "application/json", bodyReader)
}

// NewHeartbeatJobRequestWithBody constructs an http.Request for the HeartbeatJob method, with any body, and a specified content type
func NewHeartbeatJobRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s/heartbeat", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReportImagesRequest calls the generic ReportImages builder with application/json body
func NewReportImagesRequest(server string, id int, body ReportImagesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReportImagesRequestWithBody(server, id, "application/json", bodyReader)
}

// NewReportImagesRequestWithBody constructs an http.Request for the ReportImages method, with any body, and a specified content type
func NewReportImagesRequestWithBody(server string, id int, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/jobs/%s/images", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthRequest constructs an http.Request for the GetHealth method
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListJobsWithResponse List jobs with their lease and failure state
	//
	// The operator's view of the queue. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/admin/jobs (the `ListJobs` operationId).
	ListJobsWithResponse(ctx context.Context, params *ListJobsParams, reqEditors ...RequestEditorFn) (*ListJobsResponse, error)

	// AdminLoginWithResponse Complete an Access login and return to the dashboard
	//
	// Exists to be navigated to, not fetched. Access gates the path, so an unauthenticated browser is sent through the login flow and only then redirected on to `/admin`.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/admin/login (the `AdminLogin` operationId).
	AdminLoginWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AdminLoginResponse, error)

	// SubmitVideoWithBodyWithResponse Submit a YouTube URL for processing
	//
	// Creates the video row and enqueues its download job. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/admin/videos (the `SubmitVideo` operationId).
	SubmitVideoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitVideoResponse, error)

	// SubmitVideoWithResponse Submit a YouTube URL for processing
	//
	// Creates the video row and enqueues its download job. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/admin/videos (the `SubmitVideo` operationId).
	SubmitVideoWithResponse(ctx context.Context, body SubmitVideoJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitVideoResponse, error)

	// ClaimJobWithBodyWithResponse Claim the next pending job
	//
	// Atomic: the claim is a single `UPDATE ... WHERE status='pending' ... RETURNING`, so two workers polling at once cannot take the same row.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/claim (the `ClaimJob` operationId).
	ClaimJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClaimJobResponse, error)

	// ClaimJobWithResponse Claim the next pending job
	//
	// Atomic: the claim is a single `UPDATE ... WHERE status='pending' ... RETURNING`, so two workers polling at once cannot take the same row.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/claim (the `ClaimJob` operationId).
	ClaimJobWithResponse(ctx context.Context, body ClaimJobJSONRequestBody, reqEditors ...RequestEditorFn) (*ClaimJobResponse, error)

	// CompleteJobWithBodyWithResponse Report a held job as done or failed
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/{id}/complete (the `CompleteJob` operationId).
	CompleteJobWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteJobResponse, error)

	// CompleteJobWithResponse Report a held job as done or failed
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/{id}/complete (the `CompleteJob` operationId).
	CompleteJobWithResponse(ctx context.Context, id int, body CompleteJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteJobResponse, error)

	// FanOutJobWithBodyWithResponse Record what a download probed, and enqueue its chunk jobs
	//
	// Phase two of CONTEXT.md §Q13's two-phase fan-out. Idempotent on `(video_id, segment_index)`, so a download reaped mid-fan-out re-runs without duplicating the segments that already exist.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/{id}/fanout (the `FanOutJob` operationId).
	FanOutJobWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FanOutJobResponse, error)

	// FanOutJobWithResponse Record what a download probed, and enqueue its chunk jobs
	//
	// Phase two of CONTEXT.md §Q13's two-phase fan-out. Idempotent on `(video_id, segment_index)`, so a download reaped mid-fan-out re-runs without duplicating the segments that already exist.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/{id}/fanout (the `FanOutJob` operationId).
	FanOutJobWithResponse(ctx context.Context, id int, body FanOutJobJSONRequestBody, reqEditors ...RequestEditorFn) (*FanOutJobResponse, error)

	// HeartbeatJobWithBodyWithResponse Renew the lease on a held job
	//
	// Called every 30s while a job is held. Missing heartbeats are what the reaper watches for; a job whose `heartbeat_at` goes stale returns to `pending`.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/{id}/heartbeat (the `HeartbeatJob` operationId).
	HeartbeatJobWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HeartbeatJobResponse, error)

	// HeartbeatJobWithResponse Renew the lease on a held job
	//
	// Called every 30s while a job is held. Missing heartbeats are what the reaper watches for; a job whose `heartbeat_at` goes stale returns to `pending`.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/{id}/heartbeat (the `HeartbeatJob` operationId).
	HeartbeatJobWithResponse(ctx context.Context, id int, body HeartbeatJobJSONRequestBody, reqEditors ...RequestEditorFn) (*HeartbeatJobResponse, error)

	// ReportImagesWithBodyWithResponse Report the frames a chunk worker extracted, deduplicated and uploaded
	//
	// M8.4: writes the image rows and stamps the threshold and config version that produced them in the same batch, so a report can never leave the dataset with rows nobody's provenance covers. Idempotent on (video_id, timestamp_seconds), so a chunk reaped mid-report re-runs without duplicating rows (CONTEXT.md §Q14).
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/{id}/images (the `ReportImages` operationId).
	ReportImagesWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReportImagesResponse, error)

	// ReportImagesWithResponse Report the frames a chunk worker extracted, deduplicated and uploaded
	//
	// M8.4: writes the image rows and stamps the threshold and config version that produced them in the same batch, so a report can never leave the dataset with rows nobody's provenance covers. Idempotent on (video_id, timestamp_seconds), so a chunk reaped mid-report re-runs without duplicating rows (CONTEXT.md §Q14).
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /api/jobs/{id}/images (the `ReportImages` operationId).
	ReportImagesWithResponse(ctx context.Context, id int, body ReportImagesJSONRequestBody, reqEditors ...RequestEditorFn) (*ReportImagesResponse, error)

	// GetHealthWithResponse Liveness and deployment identity
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /health (the `GetHealth` operationId).
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)
}

type ListJobsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JobList
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListJobsResponse) GetJSON200() *JobList {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListJobsResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListJobsResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r ListJobsResponse) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r ListJobsResponse) GetJSON503() *ErrorResponse {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r ListJobsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListJobsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListJobsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListJobsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AdminLoginResponse302Headers the declared response headers of an HTTP 302 response for AdminLogin
type AdminLoginResponse302Headers struct {
	Location *string
}

type AdminLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *ErrorResponse
	// Headers302 the parsed response headers for an HTTP 302 response
	Headers302 *AdminLoginResponse302Headers
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r AdminLoginResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AdminLoginResponse) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r AdminLoginResponse) GetJSON503() *ErrorResponse {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r AdminLoginResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AdminLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AdminLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AdminLoginResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SubmitVideoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *VideoSubmission
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *ErrorResponse
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r SubmitVideoResponse) GetJSON201() *VideoSubmission {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SubmitVideoResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r SubmitVideoResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r SubmitVideoResponse) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r SubmitVideoResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r SubmitVideoResponse) GetJSON503() *ErrorResponse {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r SubmitVideoResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SubmitVideoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubmitVideoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SubmitVideoResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ClaimJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Job
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ClaimJobResponse) GetJSON200() *Job {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ClaimJobResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r ClaimJobResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ClaimJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ClaimJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ClaimJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CompleteJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CompleteJobResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CompleteJobResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r CompleteJobResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CompleteJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CompleteJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FanOutJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ChunkFanOut
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r FanOutJobResponse) GetJSON200() *ChunkFanOut {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r FanOutJobResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r FanOutJobResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r FanOutJobResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FanOutJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FanOutJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FanOutJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HeartbeatJobResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r HeartbeatJobResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r HeartbeatJobResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r HeartbeatJobResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HeartbeatJobResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HeartbeatJobResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HeartbeatJobResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReportImagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ImageReport
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ReportImagesResponse) GetJSON200() *ImageReport {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ReportImagesResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ReportImagesResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r ReportImagesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ReportImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReportImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReportImagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *HealthResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetHealthResponse) GetJSON200() *HealthResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListJobsWithResponse List jobs with their lease and failure state
//
// The operator's view of the queue. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/admin/jobs (the `ListJobs` operationId).
func (c *ClientWithResponses) ListJobsWithResponse(ctx context.Context, params *ListJobsParams, reqEditors ...RequestEditorFn) (*ListJobsResponse, error) {
	rsp, err := c.ListJobs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListJobsResponse(rsp)
}

// AdminLoginWithResponse Complete an Access login and return to the dashboard
//
// Exists to be navigated to, not fetched. Access gates the path, so an unauthenticated browser is sent through the login flow and only then redirected on to `/admin`.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/admin/login (the `AdminLogin` operationId).
func (c *ClientWithResponses) AdminLoginWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AdminLoginResponse, error) {
	rsp, err := c.AdminLogin(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAdminLoginResponse(rsp)
}

// SubmitVideoWithBodyWithResponse Submit a YouTube URL for processing
//
// Creates the video row and enqueues its download job. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/admin/videos (the `SubmitVideo` operationId).
func (c *ClientWithResponses) SubmitVideoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitVideoResponse, error) {
	rsp, err := c.SubmitVideoWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitVideoResponse(rsp)
}

// SubmitVideoWithResponse Submit a YouTube URL for processing
//
// Creates the video row and enqueues its download job. Requires a Cloudflare Access assertion in `Cf-Access-Jwt-Assertion` for an identity on the Worker's admin allowlist.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/admin/videos (the `SubmitVideo` operationId).
func (c *ClientWithResponses) SubmitVideoWithResponse(ctx context.Context, body SubmitVideoJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitVideoResponse, error) {
	rsp, err := c.SubmitVideo(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitVideoResponse(rsp)
}

// ClaimJobWithBodyWithResponse Claim the next pending job
//
// Atomic: the claim is a single `UPDATE ... WHERE status='pending' ... RETURNING`, so two workers polling at once cannot take the same row.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/claim (the `ClaimJob` operationId).
func (c *ClientWithResponses) ClaimJobWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ClaimJobResponse, error) {
	rsp, err := c.ClaimJobWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClaimJobResponse(rsp)
}

// ClaimJobWithResponse Claim the next pending job
//
// Atomic: the claim is a single `UPDATE ... WHERE status='pending' ... RETURNING`, so two workers polling at once cannot take the same row.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/claim (the `ClaimJob` operationId).
func (c *ClientWithResponses) ClaimJobWithResponse(ctx context.Context, body ClaimJobJSONRequestBody, reqEditors ...RequestEditorFn) (*ClaimJobResponse, error) {
	rsp, err := c.ClaimJob(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseClaimJobResponse(rsp)
}

// CompleteJobWithBodyWithResponse Report a held job as done or failed
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/{id}/complete (the `CompleteJob` operationId).
func (c *ClientWithResponses) CompleteJobWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteJobResponse, error) {
	rsp, err := c.CompleteJobWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteJobResponse(rsp)
}

// CompleteJobWithResponse Report a held job as done or failed
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/{id}/complete (the `CompleteJob` operationId).
func (c *ClientWithResponses) CompleteJobWithResponse(ctx context.Context, id int, body CompleteJobJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteJobResponse, error) {
	rsp, err := c.CompleteJob(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteJobResponse(rsp)
}

// FanOutJobWithBodyWithResponse Record what a download probed, and enqueue its chunk jobs
//
// Phase two of CONTEXT.md §Q13's two-phase fan-out. Idempotent on `(video_id, segment_index)`, so a download reaped mid-fan-out re-runs without duplicating the segments that already exist.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/{id}/fanout (the `FanOutJob` operationId).
func (c *ClientWithResponses) FanOutJobWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FanOutJobResponse, error) {
	rsp, err := c.FanOutJobWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFanOutJobResponse(rsp)
}

// FanOutJobWithResponse Record what a download probed, and enqueue its chunk jobs
//
// Phase two of CONTEXT.md §Q13's two-phase fan-out. Idempotent on `(video_id, segment_index)`, so a download reaped mid-fan-out re-runs without duplicating the segments that already exist.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/{id}/fanout (the `FanOutJob` operationId).
func (c *ClientWithResponses) FanOutJobWithResponse(ctx context.Context, id int, body FanOutJobJSONRequestBody, reqEditors ...RequestEditorFn) (*FanOutJobResponse, error) {
	rsp, err := c.FanOutJob(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFanOutJobResponse(rsp)
}

// HeartbeatJobWithBodyWithResponse Renew the lease on a held job
//
// Called every 30s while a job is held. Missing heartbeats are what the reaper watches for; a job whose `heartbeat_at` goes stale returns to `pending`.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/{id}/heartbeat (the `HeartbeatJob` operationId).
func (c *ClientWithResponses) HeartbeatJobWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HeartbeatJobResponse, error) {
	rsp, err := c.HeartbeatJobWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeartbeatJobResponse(rsp)
}

// HeartbeatJobWithResponse Renew the lease on a held job
//
// Called every 30s while a job is held. Missing heartbeats are what the reaper watches for; a job whose `heartbeat_at` goes stale returns to `pending`.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/{id}/heartbeat (the `HeartbeatJob` operationId).
func (c *ClientWithResponses) HeartbeatJobWithResponse(ctx context.Context, id int, body HeartbeatJobJSONRequestBody, reqEditors ...RequestEditorFn) (*HeartbeatJobResponse, error) {
	rsp, err := c.HeartbeatJob(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeartbeatJobResponse(rsp)
}

// ReportImagesWithBodyWithResponse Report the frames a chunk worker extracted, deduplicated and uploaded
//
// M8.4: writes the image rows and stamps the threshold and config version that produced them in the same batch, so a report can never leave the dataset with rows nobody's provenance covers. Idempotent on (video_id, timestamp_seconds), so a chunk reaped mid-report re-runs without duplicating rows (CONTEXT.md §Q14).
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/{id}/images (the `ReportImages` operationId).
func (c *ClientWithResponses) ReportImagesWithBodyWithResponse(ctx context.Context, id int, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReportImagesResponse, error) {
	rsp, err := c.ReportImagesWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReportImagesResponse(rsp)
}

// ReportImagesWithResponse Report the frames a chunk worker extracted, deduplicated and uploaded
//
// M8.4: writes the image rows and stamps the threshold and config version that produced them in the same batch, so a report can never leave the dataset with rows nobody's provenance covers. Idempotent on (video_id, timestamp_seconds), so a chunk reaped mid-report re-runs without duplicating rows (CONTEXT.md §Q14).
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /api/jobs/{id}/images (the `ReportImages` operationId).
func (c *ClientWithResponses) ReportImagesWithResponse(ctx context.Context, id int, body ReportImagesJSONRequestBody, reqEditors ...RequestEditorFn) (*ReportImagesResponse, error) {
	rsp, err := c.ReportImages(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReportImagesResponse(rsp)
}

// GetHealthWithResponse Liveness and deployment identity
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /health (the `GetHealth` operationId).
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ParseListJobsResponse parses an HTTP response from a ListJobsWithResponse call
func ParseListJobsResponse(rsp *http.Response) (*ListJobsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListJobsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseAdminLoginResponse parses an HTTP response from a AdminLoginWithResponse call
func ParseAdminLoginResponse(rsp *http.Response) (*AdminLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AdminLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 302:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	switch {
	case rsp.StatusCode == 302:
		var headers AdminLoginResponse302Headers
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		response.Headers302 = &headers
	}

	return response, nil
}

// ParseSubmitVideoResponse parses an HTTP response from a SubmitVideoWithResponse call
func ParseSubmitVideoResponse(rsp *http.Response) (*SubmitVideoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubmitVideoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest VideoSubmission
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseClaimJobResponse parses an HTTP response from a ClaimJobWithResponse call
func ParseClaimJobResponse(rsp *http.Response) (*ClaimJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ClaimJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Job
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseCompleteJobResponse parses an HTTP response from a CompleteJobWithResponse call
func ParseCompleteJobResponse(rsp *http.Response) (*CompleteJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseFanOutJobResponse parses an HTTP response from a FanOutJobWithResponse call
func ParseFanOutJobResponse(rsp *http.Response) (*FanOutJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FanOutJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChunkFanOut
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseHeartbeatJobResponse parses an HTTP response from a HeartbeatJobWithResponse call
func ParseHeartbeatJobResponse(rsp *http.Response) (*HeartbeatJobResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HeartbeatJobResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseReportImagesResponse parses an HTTP response from a ReportImagesWithResponse call
func ParseReportImagesResponse(rsp *http.Response) (*ReportImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReportImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ImageReport
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
