// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

// Defines values for CompleteRequestStatus.
const (
	Done   CompleteRequestStatus = "done"
	Failed CompleteRequestStatus = "failed"
)

// Valid indicates whether the value is a known member of the CompleteRequestStatus enum.
func (e CompleteRequestStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseService.
const (
	CrowdmonApi HealthResponseService = "crowdmon-api"
)

// Valid indicates whether the value is a known member of the HealthResponseService enum.
func (e HealthResponseService) Valid() bool {
	switch e {
	case CrowdmonApi:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for JobKind.
const (
	Chunk    JobKind = "chunk"
	Download JobKind = "download"
)

// Valid indicates whether the value is a known member of the JobKind enum.
func (e JobKind) Valid() bool {
	switch e {
	case Chunk:
		return true
	case Download:
		return true
	default:
		return false
	}
}

// ChunkWork defines model for ChunkWork.
type ChunkWork struct {
	// EndSeconds Example: 60
	EndSeconds int `json:"end_seconds"`

	// SegmentIndex Example: 0
	SegmentIndex int `json:"segment_index"`

	// StartSeconds Example: 0
	StartSeconds int `json:"start_seconds"`
}

// ClaimRequest defines model for ClaimRequest.
type ClaimRequest struct {
	// WorkerId Example: carls-ubuntu-1
	WorkerId string `json:"worker_id"`
}

// CompleteRequest defines model for CompleteRequest.
type CompleteRequest struct {
	// FailureReason Example: video unavailable
	FailureReason *string               `json:"failure_reason,omitempty"`
	Status        CompleteRequestStatus `json:"status"`

	// WorkerId Example: carls-ubuntu-1
	WorkerId string `json:"worker_id"`
}

// CompleteRequestStatus defines model for CompleteRequest.Status.
type CompleteRequestStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Example: invalid request
	Error  string             `json:"error"`
	Issues *[]ValidationIssue `json:"issues,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Environment Example: production
	Environment string                `json:"environment"`
	Service     HealthResponseService `json:"service"`
	Status      HealthResponseStatus  `json:"status"`
}

// HealthResponseService defines model for HealthResponse.Service.
type HealthResponseService string

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HeartbeatRequest defines model for HeartbeatRequest.
type HeartbeatRequest struct {
	// WorkerId Example: carls-ubuntu-1
	WorkerId string `json:"worker_id"`
}

// Job defines model for Job.
type Job struct {
	// Attempts Example: 1
	Attempts int        `json:"attempts"`
	Chunk    *ChunkWork `json:"chunk,omitempty"`

	// Id Example: 1
	Id   int     `json:"id"`
	Kind JobKind `json:"kind"`

	// VideoId Example: dQw4w9WgXcQ
	VideoId string `json:"video_id"`

	// VideoUrl Example: https://www.youtube.com/watch?v=dQw4w9WgXcQ
	VideoUrl string `json:"video_url"`
}

// JobKind defines model for JobKind.
type JobKind string

// SubmitVideoRequest defines model for SubmitVideoRequest.
type SubmitVideoRequest struct {
	// Url Example: https://www.youtube.com/watch?v=dQw4w9WgXcQ
	Url string `json:"url"`
}

// SubmitVideoResponse defines model for SubmitVideoResponse.
type SubmitVideoResponse struct {
	// JobId Example: 1
	JobId int `json:"job_id"`

	// VideoId Example: dQw4w9WgXcQ
	VideoId string `json:"video_id"`
}

// ValidationIssue defines model for ValidationIssue.
type ValidationIssue struct {
	// Message Example: Invalid URL
	Message string `json:"message"`

	// Path Example: url
	Path string `json:"path"`
}

// PostApiAdminVideosJSONRequestBody defines body for PostApiAdminVideos for application/json ContentType.
type PostApiAdminVideosJSONRequestBody = SubmitVideoRequest

// PostApiJobsClaimJSONRequestBody defines body for PostApiJobsClaim for application/json ContentType.
type PostApiJobsClaimJSONRequestBody = ClaimRequest

// PostApiJobsIdCompleteJSONRequestBody defines body for PostApiJobsIdComplete for application/json ContentType.
type PostApiJobsIdCompleteJSONRequestBody = CompleteRequest

// PostApiJobsIdHeartbeatJSONRequestBody defines body for PostApiJobsIdHeartbeat for application/json ContentType.
type PostApiJobsIdHeartbeatJSONRequestBody = HeartbeatRequest
