import "@testing-library/jest-dom/vitest";

/**
 * jsdom implements no `window.matchMedia` at all (it is not part of the DOM
 * spec jsdom targets), which is fine until a component asks for one —
 * `src/hooks/use-mobile.ts`, generated by the shadcn CLI for `Sidebar`
 * (M16), calls it unconditionally on mount. Without this stub, every test
 * that renders `AdminLayout` throws inside a `useEffect` that testing-library
 * cannot attribute to the assertion that follows it, which is a confusing
 * failure for a component the test in question may not even be about.
 * `matches: false` is an arbitrary but harmless default — nothing in this
 * app's test suite asserts on the mobile breakpoint's initial value.
 */
window.matchMedia ??= (query: string) =>
  ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false,
  }) as MediaQueryList;
